//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ace_Tuition_WBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOutstanding
    {
        public int OutID { get; set; }
        public Nullable<int> OutMonth { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<double> OutFee { get; set; }
        public Nullable<int> OutStatus { get; set; }
        public string OutDetail { get; set; }
    
        public virtual tbStudent tbStudent { get; set; }
    }
}
