//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ace_Tuition_WBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbParent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbParent()
        {
            this.tbStudents = new HashSet<tbStudent>();
        }
    
        public string ParentName { get; set; }
        public string ParentContact { get; set; }
        public Nullable<int> B40Status { get; set; }
        public Nullable<int> siblingCount { get; set; }
        public string ParentAdress { get; set; }
        public string ParentIC { get; set; }
        public int ID { get; set; }
        public string Password { get; set; }
        public Nullable<int> ParentReg { get; set; }
        public string ParentEmail { get; set; }
        public string ParentNameC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbStudent> tbStudents { get; set; }
    }
}
