//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ace_Tuition_WBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPrimary
    {
        public int PrimaryID { get; set; }
        public Nullable<double> PrimaryFee { get; set; }
        public Nullable<double> PrimaryMaterial { get; set; }
        public Nullable<int> CatID { get; set; }
    
        public virtual tbCategory tbCategory { get; set; }
    }
}
