//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ace_Tuition_WBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRegistration
    {
        public int RegID { get; set; }
        public string SubjectCode { get; set; }
        public Nullable<int> StudentID { get; set; }
    
        public virtual tbStudent tbStudent { get; set; }
    }
}
