//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ace_Tuition_WBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbReceipt
    {
        public int ReceiptID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<double> ReceiptTotal { get; set; }
        public Nullable<double> ReceiptAmount { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<double> ReceiptDiscount { get; set; }
        public string ReceiptDesc { get; set; }
        public string ReceiptProof { get; set; }
        public Nullable<int> earlyPay { get; set; }
        public Nullable<int> firstReg { get; set; }
        public Nullable<int> ReceiptStatus { get; set; }
        public Nullable<int> ReceiptOutstanding { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
    
        public virtual tbStudent tbStudent { get; set; }
    }
}
