//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ace_Tuition_WBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSecondary
    {
        public int SecondaryID { get; set; }
        public Nullable<double> SecondaryFee { get; set; }
        public Nullable<double> SecondaryMaterial { get; set; }
        public Nullable<int> CatID { get; set; }
    
        public virtual tbCategory tbCategory { get; set; }
    }
}
