//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ace_Tuition_WBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbStudent()
        {
            this.tbOutstandings = new HashSet<tbOutstanding>();
            this.tbReceipts = new HashSet<tbReceipt>();
            this.tbRegistrations = new HashSet<tbRegistration>();
        }
    
        public int StudentID { get; set; }
        public int ParentID { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> StudentCat { get; set; }
        public string StudentContact { get; set; }
        public Nullable<int> subjCount { get; set; }
        public Nullable<int> transDPW { get; set; }
        public Nullable<int> ccStat { get; set; }
        public Nullable<int> mealStat { get; set; }
        public string StudentIC { get; set; }
        public string StudentNameC { get; set; }
        public Nullable<int> writingStat { get; set; }
        public Nullable<int> StudentStandard { get; set; }
        public Nullable<int> StudentStatus { get; set; }
    
        public virtual tbCategory tbCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbOutstanding> tbOutstandings { get; set; }
        public virtual tbPackage tbPackage { get; set; }
        public virtual tbPackage tbPackage1 { get; set; }
        public virtual tbParent tbParent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReceipt> tbReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRegistration> tbRegistrations { get; set; }
        public virtual tbTransport tbTransport { get; set; }
        public virtual tbPackage tbPackage2 { get; set; }
    }
}
