//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ace_Tuition_WBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSubject
    {
        public string SubjectNames { get; set; }
        public Nullable<int> CatID { get; set; }
        public int SubjectID { get; set; }
        public string SubjectCodes { get; set; }
        public bool IsChecked { get; set; }
        public string SubjectNameC { get; set; }
    
        public virtual tbCategory tbCategory { get; set; }
    }
}
